# cloudbuild.yaml
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/scientific-air-405902/panchal-100872799/node-app:$COMMIT_SHA', '.']

  # Push docker image to artifactory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/scientific-air-405902/panchal-100872799/node-app:$COMMIT_SHA']

  # Deploy Docker container to Cloud Run using Google Cloud SDK
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy node-app \
          --image us-central1-docker.pkg.dev/scientific-air-405902/panchal-100872799/node-app:$COMMIT_SHA \
          --platform managed \
          --region us-central1

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
